const PRESET_REACTION_EMOJIS = ['❤️', '👍', '😂', '😢', '😮', '🔥']
const REACTION_PICKER_POSITION_WIDTH = 280
const REACTION_PICKER_HEIGHT = 66
const EMOJI_PICKER_HEIGHT = 350
const PICKER_GAP = 8
const VIEWPORT_MARGIN = 8

export {
  PRESET_REACTION_EMOJIS,
  REACTION_PICKER_POSITION_WIDTH,
  REACTION_PICKER_HEIGHT,
  EMOJI_PICKER_HEIGHT,
  PICKER_GAP,
  VIEWPORT_MARGIN
}
